version: '3.8'

services:
  rewriteforge:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: rewriteforge-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add your API keys here or use .env file
      # - OPENAI_API_KEY=your_openai_api_key
      # - ANTHROPIC_API_KEY=your_anthropic_api_key
      # - LLM_API_KEY=your_llm_api_key
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      # Optional: Mount logs directory for persistent logging
      - ./logs:/app/logs
    networks:
      - rewriteforge-network

  # Development service with hot reload
  rewriteforge-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rewriteforge-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - rewriteforge-network
    profiles:
      - dev

networks:
  rewriteforge-network:
    driver: bridge 